### ISSUE TITLE
Status Bar Hidden

### ISSUE THREAD

**Issue by mbalex99** [hyperoslo/ImagePicker#77]
How do I restore the status bar after presenting the image picker?

Here's a video of a recording, as you can see the status bar stays disappeared after dismissing the controller.
[Video of Issue](https://www.youtube.com/watch?v=zQE670yhLc4)

**Comment by RamonGilabert** [comment]
Hey @mbalex99! Thank's for using ImagePicker, we did that after the release, but we haven't released a new version yet, we will soon. To do that instead of using the pod as: pod 'ImagePicker', you should point to master, this was fixed here:

#71 :)

**Comment by kishykumar** [comment]
This problem still happens when the picture wrapper (wrapperDidPress) is pressed and closed. Please fix.

**Comment by richardtop** [comment]
@kishykumar I've tested, the bug is not reproducible for me. Need more information about it.

**Comment by kishykumar** [comment]
@richardtop Sorry for the late response. I tested it on iPhone 6 - iOS 10. 
Steps to reproduce: 
1. Open the Image Picker
2. Take a picture OR select an existing picture
3. Click on the Image Wrapper
4. "Close" the Image Wrapper
5. Click on "Done". 
6. Status bar is not visible

**Comment by seyhundnb** [comment]
Updated to ImagePicker 2.1.1 still not fixed, also used master branch too
